---
openstack_repository_prefix: "https://github.com/openstack-ansible/"

openstack_controller_ip: "{{ hostvars[groups.controller[0]].ansible_default_ipv4.address }}"

openstack_rabbitmq_host: "{{ openstack_controller_ip }}"
openstack_mysql_host: "{{ openstack_controller_ip }}"

openstack_identity_endpoint_host: "{{ openstack_controller_ip }}"
openstack_image_endpoint_host: "{{ openstack_controller_ip }}"
openstack_compute_endpoint_host: "{{ openstack_controller_ip }}"
openstack_network_endpoint_host: "{{ openstack_controller_ip }}"


openstack_http_proxy_environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env', 'https_proxy') }}"


openstack_no_http_proxy_environment:
    http_proxy: ''
    HTTP_PROXY: ''
    https_proxy: ''
    HTTPS_PROXY: ''
